// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmqmdnbkkkrmawdmtwtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcW1kbmJra2tybWF3ZG10d3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDc2ODUsImV4cCI6MjA2NjQyMzY4NX0.T2V-t6Dqm5oMQlpM_YNxumUR3qnE4k5Et8vCSvoTxBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);